### ISSUE TITLE
Fix test failures

### ISSUE THREAD

**Issue by feross** [xjamundx/eslint-plugin-standard#8]
Somewhere along the way, tests started failing. Must be some change in eslint.

@xjamundx - ideas?

**Comment by feross** [comment]
```
  9 failing

  1) computed-property-even-spacing invalid bar[  'foo'  ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  2) computed-property-even-spacing invalid bar['foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  3) computed-property-even-spacing invalid bar[  'foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  4) computed-property-even-spacing invalid bar[ 'foo']:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  5) computed-property-even-spacing invalid bar[
'foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  6) computed-property-even-spacing invalid bar[
'foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  7) computed-property-even-spacing invalid bar[
'foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  8) computed-property-even-spacing invalid bar[
	'foo' ]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)

  9) computed-property-even-spacing invalid bar[
	'foo'
]:
     AssertionError: Error should be a string or object.
      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:397:32)
      at Context.<anonymous> (node_modules/eslint/lib/testers/rule-tester.js:429:25)
```

**Comment by xjamundx** [comment]
I'll check it out today if it's not already fixed

**Comment by feross** [comment]
Cool, thanks!

**Comment by xjamundx** [comment]
oh we updated to eslint 2 without changing the config to support all the needed stuff or something. should be easy to fix....

**Comment by feross** [comment]
The tests were actually failing before eslint 2. I fixed up the config so that all the tests (except the 9 that were failing before) pass.

**Comment by xjamundx** [comment]
yeah ..... i hadn't run `npm i` so was seeing config related errors.

**Comment by xjamundx** [comment]
Ahh these tests were written incorrectly. I need to fill out the error objects!

```
    { code: "bar[ 'foo']", options: ['even'], errors: [1] },
    { code: "bar[\n'foo' ]", options: ['even'], errors: [1] },
    { code: "bar[\n'foo' ]", options: ['even'], errors: [1] },
    { code: "bar[\n'foo' ]", options: ['even'], errors: [1] },
    { code: "bar[\n\t'foo' ]", options: ['even'], errors: [1] },
    { code: "bar[\n\t'foo'\n]", options: ['even'], errors: [1] },

```

**Comment by feross** [comment]
Ah, nice. Shoulda taken a closer look myself before opening this.

**Comment by xjamundx** [comment]
Fixed https://github.com/xjamundx/eslint-plugin-standard/commit/60c70e1ed4a71b74e1ad7a6d58521f17d4079fb1
